"""
core/sandbox.py

===============================================================================
                                SynapseAI
===============================================================================

Secure execution environment for AI-generated Python code.

The Sandbox is responsible for safely executing code generated by
LLM-powered agents while preventing accidental modification of the
main project.

Execution Pipeline

        LLM Generated Code
                │
                ▼
      Syntax Validation (AST)
                │
                ▼
      Security Validation
                │
                ▼
      Write Temporary Script
                │
                ▼
      Execute in Workspace
                │
                ▼
      Capture Output
                │
                ▼
      Return ExecutionResult

Features
--------
✓ Syntax validation
✓ Import whitelist
✓ Forbidden import detection
✓ Timeout protection
✓ Thread-safe execution
✓ Execution logging
✓ Automatic cleanup
✓ Structured execution results
✓ Workspace isolation

===============================================================================
"""

from __future__ import annotations

import ast
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
import time
from core.guardrails import CodeGuard


from datetime import datetime
from enum import Enum
from pathlib import Path
from threading import Lock
from typing import List, Optional

from pydantic import BaseModel, Field, PrivateAttr
from zoneinfo import ZoneInfo

IST = ZoneInfo("Asia/Kolkata")

# =============================================================================
# Configuration
# =============================================================================

WORKSPACE_DIR = (
    Path(__file__).resolve().parent.parent
    / "workspace"
)

TEMP_SCRIPT_NAME = "temp_agent_script.py"

DEFAULT_TIMEOUT = 60

MAX_STDOUT_SIZE = 10_000
MAX_STDERR_SIZE = 10_000


# =============================================================================
# Security Configuration
# =============================================================================

ALLOWED_IMPORTS = {
    "numpy",
    "pandas",
    "sklearn",
    "scipy",
    "matplotlib",
    "seaborn",
    "plotly",
    "xgboost",
    "lightgbm",
    "catboost",
    "joblib",
    "pickle",
    "pathlib",
    "json",
    "math",
    "statistics",
    "collections",
    "itertools",
    "typing",
    "datetime",
    "time",
    "warnings",
    "re",
    "copy",
    "functools",
}

FORBIDDEN_IMPORTS = {
    "os",
    "sys",
    "subprocess",
    "socket",
    "requests",
    "urllib",
    "ftplib",
    "paramiko",
    "shutil",
    "multiprocessing",
    "threading",
    "ctypes",
    "resource",
    "signal",
    "psutil",
}


# =============================================================================
# Models
# =============================================================================


class SandboxError(str, Enum):
    SUCCESS = "SUCCESS"
    SYNTAX_ERROR = "SYNTAX_ERROR"
    SECURITY_ERROR = "SECURITY_ERROR"
    RUNTIME_ERROR = "RUNTIME_ERROR"
    TIMEOUT = "TIMEOUT"
    UNKNOWN = "UNKNOWN"


class ExecutionResult(BaseModel):
    """
    Result returned after sandbox execution.
    """

    success: bool

    error_type: SandboxError

    return_code: int

    stdout: str = ""

    stderr: str = ""

    execution_time: float = 0.0

    script_path: Optional[str] = None

    script_hash: Optional[str] = None

    created_at: str = Field(
        default_factory=lambda: datetime.now(IST).isoformat()
    )


# =============================================================================
# Sandbox
# =============================================================================


class Sandbox:
    """
    Secure execution environment for SynapseAI.

    Every agent executes generated Python code through this class.

    Responsibilities
    ----------------
    • Validate syntax
    • Detect unsafe imports
    • Execute inside workspace
    • Capture outputs
    • Handle timeout
    • Cleanup temporary files
    """

    def __init__(
        self,
        workspace: Path | None = None,
        timeout: int = DEFAULT_TIMEOUT,
        cleanup: bool = True,
    ):

        self.workspace = workspace or WORKSPACE_DIR
        self.guard=CodeGuard()
        self.workspace.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.timeout = timeout

        self.cleanup = cleanup

        self._lock = Lock()

    # =========================================================================
    # Helper Methods
    # =========================================================================

    def _generate_script_name(self) -> str:
        """
        Generates a unique temporary filename.
        """

        timestamp = datetime.now(IST).strftime(
            "%Y%m%d_%H%M%S_%f"
        )

        return f"agent_{timestamp}.py"

    def _script_path(self) -> Path:
        """
        Returns path for temporary script.
        """

        return self.workspace / self._generate_script_name()

    @staticmethod
    def _hash_script(script: str) -> str:
        """
        SHA256 hash of generated code.
        """

        return hashlib.sha256(
            script.encode("utf-8")
        ).hexdigest()

    @staticmethod
    def _truncate(text: str, limit: int) -> str:
        """
        Prevent extremely large stdout/stderr.
        """

        if len(text) <= limit:
            return text

        return text[:limit] + "\n\n... OUTPUT TRUNCATED ..."
    

    # =========================================================================
    # Syntax Validation
    # =========================================================================

    @staticmethod
    def validate_syntax(script: str) -> Optional[str]:
        """
        Validate Python syntax before execution.

        Returns
        -------
        None
            Script is syntactically valid.

        str
            Syntax error message.
        """

        try:
            ast.parse(script)
            return None

        except SyntaxError as e:
            return (
                f"SyntaxError: {e.msg} "
                f"(line {e.lineno}, column {e.offset})"
            )

    # =========================================================================
    # Security Validation
    # =========================================================================

    @staticmethod
    def validate_security(script: str) -> Optional[str]:
        """
        Scan generated code for dangerous imports and operations.

        Returns
        -------
        None
            Script passed validation.

        str
            Reason why execution should be rejected.
        """

        try:
            tree = ast.parse(script)

        except Exception:
            return "Unable to parse generated code."

        for node in ast.walk(tree):

            # ---------------------------------------------------------
            # import xxx
            # ---------------------------------------------------------

            if isinstance(node, ast.Import):

                for module in node.names:

                    root = module.name.split(".")[0]

                    if root in FORBIDDEN_IMPORTS:

                        return (
                            f"Forbidden import detected: '{root}'"
                        )

            # ---------------------------------------------------------
            # from xxx import ...
            # ---------------------------------------------------------

            elif isinstance(node, ast.ImportFrom):

                if node.module is None:
                    continue

                root = node.module.split(".")[0]

                if root in FORBIDDEN_IMPORTS:

                    return (
                        f"Forbidden import detected: '{root}'"
                    )

            # ---------------------------------------------------------
            # Block dangerous builtins
            # ---------------------------------------------------------

            elif isinstance(node, ast.Call):

                if isinstance(node.func, ast.Name):

                    if node.func.id in {
                        "eval",
                        "exec",
                        "compile",
                        "__import__",
                        "open",
                        "input",
                    }:

                        return (
                            f"Forbidden function call: "
                            f"{node.func.id}"
                        )

        return None

    # =========================================================================
    # Import Validation
    # =========================================================================

    @staticmethod
    def validate_imports(script: str) -> Optional[str]:
        """
        Ensure only approved libraries are imported.
        """

        tree = ast.parse(script)

        for node in ast.walk(tree):

            if isinstance(node, ast.Import):

                for module in node.names:

                    root = module.name.split(".")[0]

                    if (
                        root not in ALLOWED_IMPORTS
                        and root not in FORBIDDEN_IMPORTS
                    ):

                        return (
                            f"Unsupported library '{root}'. "
                            f"Add it to ALLOWED_IMPORTS if intended."
                        )

            elif isinstance(node, ast.ImportFrom):

                if node.module is None:
                    continue

                root = node.module.split(".")[0]

                if (
                    root not in ALLOWED_IMPORTS
                    and root not in FORBIDDEN_IMPORTS
                ):

                    return (
                        f"Unsupported library '{root}'. "
                        f"Add it to ALLOWED_IMPORTS if intended."
                    )

        return None

    # =========================================================================
    # Complete Validation
    # =========================================================================

    def validate(self, script: str) -> ExecutionResult | None:
        """
        Runs all validation checks before execution.

        Returns
        -------
        None
            Script is safe to execute.

        ExecutionResult
            Validation failed.
        """

        syntax_error = self.validate_syntax(script)

        if syntax_error:

            return ExecutionResult(
                success=False,
                error_type=SandboxError.SYNTAX_ERROR,
                return_code=-1,
                stderr=syntax_error,
            )

        security_error = self.validate_security(script)

        if security_error:

            return ExecutionResult(
                success=False,
                error_type=SandboxError.SECURITY_ERROR,
                return_code=-1,
                stderr=security_error,
            )

        import_error = self.validate_imports(script)

        if import_error:

            return ExecutionResult(
                success=False,
                error_type=SandboxError.SECURITY_ERROR,
                return_code=-1,
                stderr=import_error,
            )

        return None
    
    # =========================================================================
    # Script Management
    # =========================================================================

    def _write_script(
        self,
        script: str,
    ) -> tuple[Path, str]:
        """
        Writes generated Python code into the workspace.

        Returns
        -------
        Path
            Path of the generated script.

        str
            SHA256 hash of the script.
        """

        script_path = self._script_path()

        script_path.write_text(
            script,
            encoding="utf-8",
        )

        return script_path, self._hash_script(script)

    def _cleanup(
        self,
        script_path: Path,
    ) -> None:
        """
        Removes temporary script after successful execution.
        """

        if not self.cleanup:
            return

        try:
            if script_path.exists():
                script_path.unlink()

        except Exception:
            pass

    # =========================================================================
    # Execution
    # =========================================================================
    # ==========================================================
    # Guardrail Validation (Coming Soon)
    # ==========================================================

    # validation = self.guard.validate(script_content)
    #
    # if not validation.safe:
    #     return ExecutionResult(
    #         success=False,
    #         stdout="",
    #         stderr="\n".join(validation.errors),
    #         return_code=-1,
    #         execution_time=0.0,
    #         script_path="",
    #     )
    def execute(
        self,
        script: str,
    ) -> ExecutionResult:
        """
        Execute validated Python code.

        Pipeline
        --------
        Validation
            ↓
        Write Script
            ↓
        Execute
            ↓
        Capture Output
            ↓
        Cleanup
            ↓
        Return Result
        """

        with self._lock:

            # ------------------------------------------------------------
            # Validate
            # ------------------------------------------------------------

            validation = self.validate(script)

            if validation is not None:
                return validation

            # ------------------------------------------------------------
            # Write script
            # ------------------------------------------------------------

            script_path, script_hash = self._write_script(script)

            start = time.perf_counter()

            try:

                process = subprocess.run(
                    [sys.executable, str(script_path)],
                    cwd=self.workspace,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    # Clean execution environment env={}
                )

                elapsed = time.perf_counter() - start

                result = ExecutionResult(
                    success=process.returncode == 0,
                    error_type=(
                        SandboxError.SUCCESS
                        if process.returncode == 0
                        else SandboxError.RUNTIME_ERROR
                    ),
                    return_code=process.returncode,
                    stdout=self._truncate(
                        process.stdout,
                        MAX_STDOUT_SIZE,
                    ),
                    stderr=self._truncate(
                        process.stderr,
                        MAX_STDERR_SIZE,
                    ),
                    execution_time=elapsed,
                    script_path=str(script_path),
                    script_hash=script_hash,
                )

            except subprocess.TimeoutExpired:

                elapsed = time.perf_counter() - start

                result = ExecutionResult(
                    success=False,
                    error_type=SandboxError.TIMEOUT,
                    return_code=-1,
                    stderr=f"Execution exceeded {self.timeout} seconds.",
                    execution_time=elapsed,
                    script_path=str(script_path),
                    script_hash=script_hash,
                )

            except Exception as e:

                elapsed = time.perf_counter() - start

                result = ExecutionResult(
                    success=False,
                    error_type=SandboxError.UNKNOWN,
                    return_code=-1,
                    stderr=str(e),
                    execution_time=elapsed,
                    script_path=str(script_path),
                    script_hash=script_hash,
                )

            # ------------------------------------------------------------
            # Cleanup
            # ------------------------------------------------------------

            if result.success:
                self._cleanup(script_path)

            return result

    # =========================================================================
    # Convenience API
    # =========================================================================

    def __call__(
        self,
        script: str,
    ) -> ExecutionResult:
        """
        Allows:

            result = sandbox(code)
        """

        return self.execute(script)