"""
agents/critic_agent.py

===============================================================================
                                SynapseAI
===============================================================================

Critic Agent

Responsibilities
----------------
✓ Validate generated model artifacts
✓ Detect overfitting / underfitting
✓ Detect suspicious model behaviour
✓ Review leaderboard quality
✓ Produce deterministic feedback
✓ Decide whether another iteration is required
✓ Update AgentState

The Critic Agent is intentionally hybrid.

Stage 1 (ACTIVE — Part 1)
--------------------------
Rule-based deterministic validation.

Stage 2 (READY — Part 2)
--------------------------
LLM reasoning layered on top of Stage 1.
To activate Part 2, replace run() with run_v2() below.

===============================================================================
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

import pandas as pd

from agents.base_agent import BaseAgent


class CriticAgent(BaseAgent):
    """
    Autonomous evaluation agent.

    The critic does NOT train models.

    Instead it evaluates the outputs generated by ModelAgent and
    determines whether another AutoML iteration is required.
    """

    # ------------------------------------------------------------------
    # Thresholds
    # ------------------------------------------------------------------

    OVERFITTING_GAP = 0.10

    MIN_ACCEPTABLE_SCORE = 0.60

    MIN_CANDIDATE_MODELS = 3

    def __init__(
        self,
        state,
        llm,
        sandbox,
    ):

        super().__init__(
            state,
            llm,
            sandbox,
        )

        self.feedback: List[str] = []

        self.leaderboard = None

        self.metrics = {}

    # ==========================================================
    # Helpers
    # ==========================================================

    def add_feedback(self, message: str):
        """Store deterministic feedback."""

        self.feedback.append(message)
        self.log(message)

    # ==========================================================
    # Artifact Validation
    # ==========================================================

    def validate_artifacts(self) -> bool:
        """Ensure ModelAgent produced all expected outputs."""

        required = [
            self.state.best_model_path,
            self.state.leaderboard_path,
            self.state.metrics_path,
        ]

        missing = []

        for artifact in required:

            if artifact is None:
                missing.append("None")
                continue

            if not Path(artifact).exists():
                missing.append(artifact)

        if missing:

            self.error(
                "Missing model artifacts:\n"
                + "\n".join(missing)
            )

            self.add_feedback(
                "Model artifacts are incomplete."
            )

            self.state.retry_required = True

            return False

        return True

    # ==========================================================
    # Loading
    # ==========================================================

    def load_metrics(self):
        """Read metrics.json"""

        with open(
            self.state.metrics_path,
            "r",
            encoding="utf-8",
        ) as f:
            self.metrics = json.load(f)

    def load_leaderboard(self):
        """Read leaderboard.csv"""

        self.leaderboard = pd.read_csv(
            self.state.leaderboard_path
        )

        if self.leaderboard.empty:
            raise ValueError("Leaderboard is empty.")

    # ==========================================================
    # Basic Checks
    # ==========================================================

    def check_candidate_models(self):
        """Ensure enough candidate models were evaluated."""

        total = len(self.leaderboard)

        if total < self.MIN_CANDIDATE_MODELS:

            self.add_feedback(
                f"Only {total} candidate models were trained."
            )

            self.state.retry_required = True

    def check_best_score(self):
        """Detect weak overall model performance."""

        score = self.metrics.get("best_score", None)

        if score is None:

            self.add_feedback(
                "Metrics file does not contain best_score."
            )

            self.state.retry_required = True

            return

        if score < self.MIN_ACCEPTABLE_SCORE:

            self.add_feedback(
                f"Best score ({score:.4f}) is below the "
                f"minimum acceptable threshold "
                f"({self.MIN_ACCEPTABLE_SCORE:.2f})."
            )

            self.state.retry_required = True

    def check_problem_type(self):
        """Ensure ModelAgent correctly detected task type."""

        problem = self.metrics.get("problem_type", None)

        if problem not in {
            "classification",
            "regression",
            "binary",
            "multiclass",
        }:

            self.add_feedback(
                "Unknown problem type detected."
            )

            self.state.retry_required = True

    # ==========================================================
    # Leaderboard Validation
    # ==========================================================

    def check_leaderboard_consistency(self):
        """Validate leaderboard structure and ranking."""

        required_columns = {
            "Model Name",
            "Evaluation Metric",
            "Score",
            "Training Time",
        }

        missing = required_columns - set(self.leaderboard.columns)

        if missing:

            self.add_feedback(
                f"Leaderboard missing columns: {sorted(missing)}"
            )

            self.state.retry_required = True
            return

        if self.leaderboard["Score"].isnull().any():

            self.add_feedback(
                "Leaderboard contains missing scores."
            )

            self.state.retry_required = True

        if not self.leaderboard["Score"].is_monotonic_decreasing:

            self.add_feedback(
                "Leaderboard is not sorted by score."
            )

        if self.leaderboard["Model Name"].duplicated().any():

            self.add_feedback(
                "Duplicate models detected in leaderboard."
            )

    # ==========================================================
    # Performance Analysis
    # ==========================================================

    def detect_overfitting(self):
        """Compare train/test metrics if available."""

        train_score = self.metrics.get("train_score")
        test_score = self.metrics.get("best_score")

        if train_score is None or test_score is None:
            return

        gap = train_score - test_score

        if gap > self.OVERFITTING_GAP:

            self.state.overfitting_detected = True

            self.add_feedback(
                f"Possible overfitting detected (gap={gap:.4f})."
            )

            self.state.retry_required = True

    def detect_underfitting(self):
        """Detect consistently poor performance."""

        score = self.metrics.get("best_score")

        if score is None:
            return

        if score < 0.50:

            self.add_feedback(
                "Model appears to be underfitting."
            )

            self.state.retry_required = True

    def detect_metric_anomalies(self):
        """Look for impossible metric values."""

        for key, value in self.metrics.items():

            if not isinstance(value, (int, float)):
                continue

            if "score" in key.lower():

                if value < 0 or value > 1:

                    self.add_feedback(
                        f"Invalid metric '{key}'={value}"
                    )

                    self.state.retry_required = True

        if len(self.feedback) == 0:

            self.add_feedback(
                "No deterministic issues detected."
            )

    # ==========================================================
    # Summary
    # ==========================================================

    def generate_summary(self):

        return {
            "best_model": self.metrics.get("best_model"),
            "best_score": self.metrics.get("best_score"),
            "problem_type": self.metrics.get("problem_type"),
            "feedback": self.feedback,
            "retry_required": self.state.retry_required,
            "overfitting": self.state.overfitting_detected,
        }

    # ==========================================================
    # Part 1 — Active run() — Deterministic evaluation only
    # ==========================================================

    def run(self):

        self.log("Starting model evaluation.")

        # ------------------------------------------------------
        # Validate required artifacts
        # ------------------------------------------------------

        if not self.validate_artifacts():
            self.complete()
            return self.state

        # ------------------------------------------------------
        # Load artifacts
        # ------------------------------------------------------

        try:

            self.load_metrics()
            self.load_leaderboard()

        except Exception as e:

            self.error(
                f"Unable to load model artifacts:\n{e}"
            )

            self.state.retry_required = True
            self.complete()
            return self.state

        # ------------------------------------------------------
        # Deterministic evaluation
        # ------------------------------------------------------

        self.check_candidate_models()
        self.check_problem_type()
        self.check_best_score()
        self.check_leaderboard_consistency()
        self.detect_overfitting()
        self.detect_underfitting()
        self.detect_metric_anomalies()

        summary = self.generate_summary()

        # ------------------------------------------------------
        # Store critic feedback
        # ------------------------------------------------------

        self.state.critic_feedback = self.feedback.copy()

        self.state.log_execution(
            agent=self.name,
            action="Deterministic model evaluation",
            status="SUCCESS",
            details=json.dumps(summary, indent=4),
        )

        self.state.log_decision(
            agent=self.name,
            decision="Deterministic evaluation completed.",
        )

        self.log("Critic evaluation completed.")

        # ------------------------------------------------------
        # Temporary workflow decision
        #
        # Part 2 will replace this block with the hybrid
        # decision engine (determine_next_phase) that uses
        # LLM reasoning on top of these deterministic findings.
        #
        # To activate Part 2, call run_v2() instead of run().
        # ------------------------------------------------------

        if self.state.retry_required:

            self.log(
                "Retry requested by deterministic checks."
            )

            # Part 2 will intelligently choose between returning
            # to FEATURE_ENGINEERING vs MODELING based on the
            # specific failure detected. For now we always retry
            # the modeling stage.
            self.set_phase("MODELING")

        else:

            self.log(
                "Model accepted by deterministic checks."
            )

            self.set_phase("REPORT")

        self.complete()
        self.reset_retry()

        return self.state

    # ==========================================================
    # Part 2 — LLM review methods
    # ==========================================================
    # These are ready to use. To activate Part 2, swap run()
    # for run_v2() (rename run → run_v1, run_v2 → run).
    # ==========================================================

    def build_llm_prompt(self) -> str:
        """Build a comprehensive prompt for the LLM."""

        leaderboard = self.leaderboard.to_string(index=False)

        feedback = (
            "\n".join(f"- {item}" for item in self.feedback)
            if self.feedback
            else "None"
        )

        return f"""
You are SynapseAI's autonomous Critic Agent.

Your responsibility is to review the results produced by an AutoML
pipeline.

You MUST NOT invent information.

Evaluate only the supplied information.

========================================================

Problem Type

========================================================

{self.metrics.get("problem_type")}

========================================================

Best Model

========================================================

{self.metrics.get("best_model")}

========================================================

Best Score

========================================================

{self.metrics.get("best_score")}

========================================================

Model Leaderboard

========================================================

{leaderboard}

========================================================

Deterministic Findings

========================================================

{feedback}

========================================================

Provide a concise review covering:

1. Overall model quality.

2. Signs of overfitting.

3. Signs of underfitting.

4. Whether feature engineering should be improved.

5. Whether more models should be trained.

6. Weaknesses.

7. Strengths.

8. Recommended next action.

Return plain text only.
"""

    def llm_review(self) -> str:
        """Append LLM critique to critic_feedback in state."""

        self.log("Generating LLM critique.")

        prompt = self.build_llm_prompt()

        review = self.ask_llm(
            prompt=prompt,
            system_prompt="You are an expert machine learning reviewer.",
        )

        self.state.critic_feedback.append(
            "\n===== LLM REVIEW =====\n"
        )

        self.state.critic_feedback.append(review)

        self.log("LLM critique generated.")

        return review

    def determine_next_phase(self):
        """
        Hybrid decision engine.

        Reads self.state.critic_feedback (which by this point contains
        both deterministic findings and the LLM review text) and sets
        the next workflow phase.

        Called by run_v2() AFTER llm_review() has been invoked.

        BUG FIX: The original implementation called self.determine_next_phase()
        recursively, causing infinite recursion / stack overflow.
        It also contained workflow completion code (self.complete(),
        self.reset_retry()) that belongs in run(), not here.
        This method is now a pure decision function with no side effects
        beyond setting the phase and retry flag.
        """

        review = "\n".join(self.state.critic_feedback).lower()

        # Overfitting takes highest priority — return to feature engineering
        if self.state.overfitting_detected:

            self.log(
                "Decision: overfitting detected — return to Feature Engineering."
            )

            self.set_phase("FEATURE_ENGINEERING")
            self.state.retry_required = True
            return

        # LLM explicitly recommends feature engineering
        if any(
            word in review
            for word in [
                "feature engineering",
                "feature selection",
                "feature importance",
            ]
        ):

            self.log(
                "LLM recommends feature engineering."
            )

            self.set_phase("FEATURE_ENGINEERING")
            self.state.retry_required = True
            return

        # LLM recommends more model training / tuning
        if any(
            word in review
            for word in [
                "hyperparameter",
                "train more models",
                "additional models",
                "model selection",
            ]
        ):

            self.log(
                "LLM recommends another modeling iteration."
            )

            self.set_phase("MODELING")
            self.state.retry_required = True
            return

        # All checks passed — accept the model
        self.log("Critic accepts current model.")
        self.state.retry_required = False
        self.set_phase("REPORT")

    def run_v2(self):
        """
        Part 2 run() — Hybrid deterministic + LLM evaluation.

        Replaces run() when LLM critique is ready.
        To activate: rename run → run_v1, run_v2 → run.
        """

        self.log("Starting hybrid model evaluation.")

        # ------------------------------------------------------
        # Validate required artifacts
        # ------------------------------------------------------

        if not self.validate_artifacts():
            self.complete()
            return self.state

        # ------------------------------------------------------
        # Load artifacts
        # ------------------------------------------------------

        try:

            self.load_metrics()
            self.load_leaderboard()

        except Exception as e:

            self.error(
                f"Unable to load model artifacts:\n{e}"
            )

            self.state.retry_required = True
            self.complete()
            return self.state

        # ------------------------------------------------------
        # Deterministic evaluation
        # ------------------------------------------------------

        self.check_candidate_models()
        self.check_problem_type()
        self.check_best_score()
        self.check_leaderboard_consistency()
        self.detect_overfitting()
        self.detect_underfitting()
        self.detect_metric_anomalies()

        summary = self.generate_summary()

        # Store deterministic feedback before LLM adds to it
        self.state.critic_feedback = self.feedback.copy()

        self.state.log_execution(
            agent=self.name,
            action="Deterministic model evaluation",
            status="SUCCESS",
            details=json.dumps(summary, indent=4),
        )

        self.state.log_decision(
            agent=self.name,
            decision="Deterministic evaluation completed.",
        )

        # ------------------------------------------------------
        # LLM critique (appends to self.state.critic_feedback)
        # ------------------------------------------------------

        try:

            self.llm_review()

        except Exception as e:

            self.error(f"LLM critique failed:\n{e}")

            self.state.log_decision(
                agent=self.name,
                decision="Continuing using deterministic evaluation only.",
            )

        # ------------------------------------------------------
        # Hybrid decision engine
        # (reads the now-complete critic_feedback including LLM)
        # ------------------------------------------------------

        self.determine_next_phase()

        # ------------------------------------------------------
        # Log the final decision
        # ------------------------------------------------------

        if self.state.retry_required:

            self.state.log_decision(
                agent=self.name,
                decision=(
                    f"Retry requested. Returning to "
                    f"{self.state.current_phase}."
                ),
            )

        else:

            self.state.log_decision(
                agent=self.name,
                decision="Model accepted. Proceeding to report generation.",
            )

        # ------------------------------------------------------
        # Workflow
        # ------------------------------------------------------

        self.complete()
        self.reset_retry()

        self.log("CriticAgent finished successfully.")

        return self.state